# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/wildfire_visualization',
                'doc_host': 'https://mmwitters.github.io',
                'git_url': 'https://github.com/mmwitters/wildfire_visualization',
                'lib_path': 'wildfire_visualization'},
  'syms': {'wildfire_visualization.core': {'wildfire_visualization.core.foo': ('core.html#foo', 'wildfire_visualization/core.py')}}}
